services:
  - type: web
    name: kincare-api
    runtime: docker
    dockerfilePath: src/KinCare.API/Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: kincare-db
          property: connectionString
      - key: Jwt__SecretKey
        generateValue: true
      - key: App__BaseUrl
        value: https://kincare-web.onrender.com
      - key: Cors__AllowedOrigins__0
        value: https://kincare-web.onrender.com
      - key: Twilio__AccountSid
        sync: false
      - key: Twilio__AuthToken
        sync: false
      - key: Twilio__FromNumber
        sync: false
      - key: Splunk__HecUrl
        sync: false
      - key: Splunk__HecToken
        sync: false
      - key: Stripe__SecretKey
        sync: false
      - key: Stripe__WebhookSecret
        sync: false
      - key: Stripe__StarterPriceId
        sync: false
      - key: Stripe__ProfessionalPriceId
        sync: false
      - key: Stripe__EnterprisePriceId
        sync: false
      - key: SendGrid__ApiKey
        sync: false
      - key: SendGrid__FromEmail
        sync: false
      - key: Broker__ApiKey
        sync: false
      - key: Broker__ClientId
        sync: false
      - key: Broker__ClientSecret
        sync: false
      - key: Broker__OrganizationId
        sync: false
      - key: Broker__WebhookSecret
        sync: false
      - key: LocationIq__ApiKey
        sync: false

  - type: web
    runtime: static
    name: kincare-web
    buildCommand: cd src/KinCare.Web && npm install && npm run build
    staticPublishPath: src/KinCare.Web/dist/kin-care.web/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: API_BASE_URL
        value: https://kincare-api-98e1.onrender.com
      - key: LOCATIONIQ_API_KEY
        sync: false

databases:
  - name: kincare-db
    databaseName: kincare
    user: kincare
    plan: free
